version: '3.4'

services:
  service:
    image: saladbowl-service
    container_name: saladbowl-service
    build: ./service
    ports:
      - 8080:8080

  web:
    image: saladbowl-web
    container_name: saladbowl-web
    build: ./webapp
    ports:
      - 3000:3000
