version: '3'

tasks:
  precommit:
    summary: Runs through all local tests to verify commit
    cmds:
      - go clean -testcache ./...
      - task test
      - task up
      - task e2e
      - task down
    silent: true

  up:
    cmds:
      - docker-compose up --build -d
    silent: true

  down:
    cmds:
      - docker-compose down
    silent: true

  e2e:
    cmds:
      - cd e2e && npm run test
    silent: true

  generate:
    cmds:
      - go generate ./...
    silent: true

  test:
    cmds:
      - go test ./...
    silent: true
