version: '3'

includes:
  service: 
    taskfile: ./service/Taskfile.yml
    dir: ./service

  webapp:
    taskfile: ./webapp/Taskfile.yml
    dir: ./webapp

tasks:
  start:
    cmds:
      - |
        source ./scripts/functions.sh;
        prefix-green "service" task service:start &
        prefix-yellow "webapp" task webapp:start &
        wait

      # Find the background processes by port number and kill them
      - |
        source ./scripts/functions.sh;
        kill-process-by-port 8080
        kill-process-by-port 3000
