version: '3'

includes:
  service: 
    taskfile: ./apps/service/Taskfile.yml
    dir: ./apps/service

  webapp:
    taskfile: ./apps/webapp/Taskfile.yml
    dir: ./apps/webapp

tasks:
  dev-all:
    cmds:
      # Start the 'dev' task for service and webapp, as background processes
      - |
        source ./scripts/functions.sh;
        prefix-green "service" task service:dev &
        prefix-yellow "webapp" task webapp:dev &
        wait

      # Find the background processes by port number and kill them
      - |
        source ./scripts/functions.sh;
        kill-process-by-port 8080
        kill-process-by-port 3000
