version: '3'

tasks:
  run:
    cmds:
      - go run main.go
    silent: true

  e2e:
    cmds:
      - docker-compose up --build -d
      - cd e2e && npm run test
      - docker-compose down
    silent: true

  generate:
    cmds:
      - go generate ./...
    silent: true

  test:
    cmds:
      - go test ./...
    silent: true
