version: '3'


tasks:
  build:
    cmds:
      - go build cmd/app/app.go

  run:
    cmds:
      - go run cmd/app/app.go

  dev:
    cmds:
      - air --build.cmd "task build" --build.bin "./app"

  test:
    cmds:
      - go test ./...

  test-cover:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out 