version: '3'


tasks:
  install:
    cmds:
      - go mod tidy
      - cd e2e && npm i

  build:
    cmds:
      - go build cmd/app/app.go

  run:
    cmds:
      - go run cmd/app/app.go

  dev:
    cmds:
      - air --build.cmd "task build" --build.bin "./app"

  test:
    cmds:
      - go test ./...

  test-cover:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out 

  e2e:
    dir: e2e
    cmds:
      - npx jest
  
  precommit:
    - task: build
    - task: test