version: '3'


tasks:
  start:
    cmds:
      - air --build.cmd "go build cmd/app/app.go" --build.bin "./app"

  test:
    cmds:
      - go test ./...

  test-cover:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out 

  e2e:
    dir: e2e
    cmds:
      - npx jest

  e2e-docker:
    desc: Run the app and e2e test suite in docker containers
    cmds:
      - defer: docker rm -f saladbowl-service
      - defer: docker rm -f saladbowl-service-e2e
      - docker build -t saladbowl-service-e2e -f ./e2e/Dockerfile ./e2e
      - docker build -t saladbowl-service ./
      - docker run --network host -d --name saladbowl-service saladbowl-service
      - docker run --network host --name saladbowl-service-e2e saladbowl-service-e2e
  
  precommit:
    - task: build
    - task: test