// Code generated by mockery v2.30.1. DO NOT EDIT.

package hub

import mock "github.com/stretchr/testify/mock"

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

type MockHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHub) EXPECT() *MockHub_Expecter {
	return &MockHub_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function with given fields: message
func (_m *MockHub) Broadcast(message Message) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHub_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockHub_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - message Message
func (_e *MockHub_Expecter) Broadcast(message interface{}) *MockHub_Broadcast_Call {
	return &MockHub_Broadcast_Call{Call: _e.mock.On("Broadcast", message)}
}

func (_c *MockHub_Broadcast_Call) Run(run func(message Message)) *MockHub_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Message))
	})
	return _c
}

func (_c *MockHub_Broadcast_Call) Return(_a0 error) *MockHub_Broadcast_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHub_Broadcast_Call) RunAndReturn(run func(Message) error) *MockHub_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// HandleNewConnection provides a mock function with given fields: playerChannel
func (_m *MockHub) HandleNewConnection(playerChannel PlayerChannel) {
	_m.Called(playerChannel)
}

// MockHub_HandleNewConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleNewConnection'
type MockHub_HandleNewConnection_Call struct {
	*mock.Call
}

// HandleNewConnection is a helper method to define mock.On call
//   - playerChannel PlayerChannel
func (_e *MockHub_Expecter) HandleNewConnection(playerChannel interface{}) *MockHub_HandleNewConnection_Call {
	return &MockHub_HandleNewConnection_Call{Call: _e.mock.On("HandleNewConnection", playerChannel)}
}

func (_c *MockHub_HandleNewConnection_Call) Run(run func(playerChannel PlayerChannel)) *MockHub_HandleNewConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(PlayerChannel))
	})
	return _c
}

func (_c *MockHub_HandleNewConnection_Call) Return() *MockHub_HandleNewConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_HandleNewConnection_Call) RunAndReturn(run func(PlayerChannel)) *MockHub_HandleNewConnection_Call {
	_c.Call.Return(run)
	return _c
}

// HandleReconnection provides a mock function with given fields: playerChannel, playerId
func (_m *MockHub) HandleReconnection(playerChannel PlayerChannel, playerId string) {
	_m.Called(playerChannel, playerId)
}

// MockHub_HandleReconnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReconnection'
type MockHub_HandleReconnection_Call struct {
	*mock.Call
}

// HandleReconnection is a helper method to define mock.On call
//   - playerChannel PlayerChannel
//   - playerId string
func (_e *MockHub_Expecter) HandleReconnection(playerChannel interface{}, playerId interface{}) *MockHub_HandleReconnection_Call {
	return &MockHub_HandleReconnection_Call{Call: _e.mock.On("HandleReconnection", playerChannel, playerId)}
}

func (_c *MockHub_HandleReconnection_Call) Run(run func(playerChannel PlayerChannel, playerId string)) *MockHub_HandleReconnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(PlayerChannel), args[1].(string))
	})
	return _c
}

func (_c *MockHub_HandleReconnection_Call) Return() *MockHub_HandleReconnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_HandleReconnection_Call) RunAndReturn(run func(PlayerChannel, string)) *MockHub_HandleReconnection_Call {
	_c.Call.Return(run)
	return _c
}

// OnMessage provides a mock function with given fields: cb
func (_m *MockHub) OnMessage(cb PlayerMessageCallback) {
	_m.Called(cb)
}

// MockHub_OnMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnMessage'
type MockHub_OnMessage_Call struct {
	*mock.Call
}

// OnMessage is a helper method to define mock.On call
//   - cb PlayerMessageCallback
func (_e *MockHub_Expecter) OnMessage(cb interface{}) *MockHub_OnMessage_Call {
	return &MockHub_OnMessage_Call{Call: _e.mock.On("OnMessage", cb)}
}

func (_c *MockHub_OnMessage_Call) Run(run func(cb PlayerMessageCallback)) *MockHub_OnMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(PlayerMessageCallback))
	})
	return _c
}

func (_c *MockHub_OnMessage_Call) Return() *MockHub_OnMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_OnMessage_Call) RunAndReturn(run func(PlayerMessageCallback)) *MockHub_OnMessage_Call {
	_c.Call.Return(run)
	return _c
}

// OnNewConnection provides a mock function with given fields: cb
func (_m *MockHub) OnNewConnection(cb NewConnectionCallback) {
	_m.Called(cb)
}

// MockHub_OnNewConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnNewConnection'
type MockHub_OnNewConnection_Call struct {
	*mock.Call
}

// OnNewConnection is a helper method to define mock.On call
//   - cb NewConnectionCallback
func (_e *MockHub_Expecter) OnNewConnection(cb interface{}) *MockHub_OnNewConnection_Call {
	return &MockHub_OnNewConnection_Call{Call: _e.mock.On("OnNewConnection", cb)}
}

func (_c *MockHub_OnNewConnection_Call) Run(run func(cb NewConnectionCallback)) *MockHub_OnNewConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(NewConnectionCallback))
	})
	return _c
}

func (_c *MockHub_OnNewConnection_Call) Return() *MockHub_OnNewConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_OnNewConnection_Call) RunAndReturn(run func(NewConnectionCallback)) *MockHub_OnNewConnection_Call {
	_c.Call.Return(run)
	return _c
}

// OnPlayerDisconnect provides a mock function with given fields: cb
func (_m *MockHub) OnPlayerDisconnect(cb PlayerDisconnectCallback) {
	_m.Called(cb)
}

// MockHub_OnPlayerDisconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerDisconnect'
type MockHub_OnPlayerDisconnect_Call struct {
	*mock.Call
}

// OnPlayerDisconnect is a helper method to define mock.On call
//   - cb PlayerDisconnectCallback
func (_e *MockHub_Expecter) OnPlayerDisconnect(cb interface{}) *MockHub_OnPlayerDisconnect_Call {
	return &MockHub_OnPlayerDisconnect_Call{Call: _e.mock.On("OnPlayerDisconnect", cb)}
}

func (_c *MockHub_OnPlayerDisconnect_Call) Run(run func(cb PlayerDisconnectCallback)) *MockHub_OnPlayerDisconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(PlayerDisconnectCallback))
	})
	return _c
}

func (_c *MockHub_OnPlayerDisconnect_Call) Return() *MockHub_OnPlayerDisconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_OnPlayerDisconnect_Call) RunAndReturn(run func(PlayerDisconnectCallback)) *MockHub_OnPlayerDisconnect_Call {
	_c.Call.Return(run)
	return _c
}

// SendTo provides a mock function with given fields: playerId, message
func (_m *MockHub) SendTo(playerId string, message Message) error {
	ret := _m.Called(playerId, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, Message) error); ok {
		r0 = rf(playerId, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHub_SendTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTo'
type MockHub_SendTo_Call struct {
	*mock.Call
}

// SendTo is a helper method to define mock.On call
//   - playerId string
//   - message Message
func (_e *MockHub_Expecter) SendTo(playerId interface{}, message interface{}) *MockHub_SendTo_Call {
	return &MockHub_SendTo_Call{Call: _e.mock.On("SendTo", playerId, message)}
}

func (_c *MockHub_SendTo_Call) Run(run func(playerId string, message Message)) *MockHub_SendTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(Message))
	})
	return _c
}

func (_c *MockHub_SendTo_Call) Return(_a0 error) *MockHub_SendTo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHub_SendTo_Call) RunAndReturn(run func(string, Message) error) *MockHub_SendTo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
