version: '3'

tasks:
  install:
    cmds:
      - npm i

  build:
    sources:
      - ./src/**/*
      - ./node_modules/**/*
      - ./package*.json
    generates:
      - ./dist/**/*
    cmds:
      - npm run build 

  dev:
    cmds:
      - npx vite --open

  test:
    cmds:
      - npx vitest run

  test-watch:
    cmds:
      - npx vitest watch

  test-cover:
    cmds:
      - npx vitest run --coverage
      - open ./coverage/index.html
  e2e:
    cmds:
      - echo 'TODO'